### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by Cu-chi**
### Update fr.json

Modified "off" by "Désactivé": _because you have set "Activé" for "On" so logically in French for "Off" we will say "Désactivé"._
Removed the space before the suspension points: _for once, it's like in English_

### CODE REVIEW

**Comment by TGRHavoc** [comment]
Looks good. 
Could you change the commit message to [follow the commit format?](https://github.com/TGRHavoc/live_map-interface/blob/develop/docs/contributing.md#commit-messages).

I would suggest `translation(fr): update generic.off/reconnection` followed by the body, amd if you're doing multiple changes then a commit per change would be nice :). It'll allow me to add your changes to the changelog when it gets released :D

**Comment by Cu-chi** [comment]
Is it good?

**Comment by TGRHavoc** [comment]
Yeah, I'll merge when I'm at my computer :)

**Review by TGRHavoc — APPROVED** [review]

**Comment by TGRHavoc** [comment]
Merged with b8c7102ca4baf2ab1eaead49c4fcf622eaa90606

**Pull request closed without merging**
